site_name: depthcharge
repo_url: https://github.com/wfondrie/depthcharge
nav:
  - Home: "README.md"
  - API: "api/index.md"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
  logo: static/icon.svg
  favicon: static/icon.svg
  font:
    text: Fira Code
  palette:
    scheme: depthcharge

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_heading: true
            heading_level: 3
            docstring_section_style: spacy
            show_source: false
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
              trim_doctest_flags: true

markdown_extensions:
  - attr_list
  - smarty
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wfondrie
