site_name: depthcharge
repo_url: https://github.com/wfondrie/depthcharge
nav:
  - Getting Started:
      - Introduction: "index.md"
      - Installation: "getting-started/installation.md"
      - Modeling Mass Spectra: "getting-started/spectra.md"
  - API:
      - Overview: "api/index.md"
      - Tokenizers: "api/tokenizers.md"
      - Datasets: "api/datasets.md"
      - Encoders: "api/encoders.md"
      - Transformers: "api/transformers.md"
      - Primitives: "api/primitives.md"
  - Changelog: CHANGELOG.md
  - Contributing: CONTRIBUTING.md
  - Code of Conduct: CODE_OF_CONDUCT.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.footer
    - content.code.copy
  logo: static/icon.svg
  favicon: static/icon.svg
  font:
    text: Fira Code
    code: Fira Code
  palette:
    scheme: depthcharge

extra_css:
  - stylesheets/extra.css

plugins:
  - mkquartodocs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_heading: true
            show_root_full_path: false
            heading_level: 2
            docstring_section_style: spacy
            show_source: false
            merge_init_into_class: true
            group_by_category: true
            show_category_heading: true
            docstring_options:
              ignore_init_summary: true
              trim_doctest_flags: true

            inherited_members: true
            members:
            filters: ["!^_", "!^__"]

markdown_extensions:
  - attr_list
  #- smarty
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wfondrie
  version:
    provider: mike
